name: Build and run tests
on:
  push:
    branches-ignore:
      - master
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run:  ./gradlew build
      - name: Run integration tests
        run: ./gradlew component-tests:componentTests